CREATE TABLE if not exists "company_conf"
(
    id                  INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    company_name        VARCHAR(255),
    company_description TEXT,
    company_phone       VARCHAR(255),
    company_slogan      VARCHAR(255),
    company_logo_base64 TEXT,
    nif                 VARCHAR(255),
    stat                VARCHAR(255),
    rcs                 VARCHAR(255),
    company_email       VARCHAR(255),
    company_address     VARCHAR(255),
    CONSTRAINT pk_companyconf PRIMARY KEY (id)
);