CREATE TABLE if not exists "phone_number_entity"
(
    id           INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    phone_number VARCHAR(255),
    country_code VARCHAR(255),
    employee_id  INTEGER,
    CONSTRAINT pk_phonenumberentity PRIMARY KEY (id)
);

ALTER TABLE phone_number_entity
    ADD CONSTRAINT UniquePhoneNumbers UNIQUE (phone_number, country_code);

ALTER TABLE phone_number_entity
    ADD CONSTRAINT FK_PHONENUMBERENTITY_ON_EMPLOYEE FOREIGN KEY (employee_id) REFERENCES employee_entity (id);