CREATE TABLE if not exists "users"
(
    id               INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    unique_user_name VARCHAR(255),
    password         VARCHAR(255),
    CONSTRAINT pk_users PRIMARY KEY (id)
);

ALTER TABLE users
    ADD CONSTRAINT uc_users_uniqueusername UNIQUE (unique_user_name);